spring:
  config:
    activate:
      on-profile: test
application:
  name: test-YAML
  environment: testing
  enabled: false
  servers:
  - www.abc.test.com
  - www.xyz.test.com

---
spring:
  config:
    activate:
      on-profile: prod
application:
  name: prod-YAML
  environment: production
  enabled: true
  servers:
  - www.abc.prod.com
  - www.xyz.prod.com
